package SquaredApp;


/**
* SquaredApp/Squared.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Squared.idl
* Saturday, April 10, 2021 8:59:48 PM SGT
*/

public interface Squared extends SquaredOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Squared
