package SquaredApp;

/**
* SquaredApp/SquaredHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Squared.idl
* Saturday, April 10, 2021 8:59:48 PM SGT
*/

public final class SquaredHolder implements org.omg.CORBA.portable.Streamable
{
  public SquaredApp.Squared value = null;

  public SquaredHolder ()
  {
  }

  public SquaredHolder (SquaredApp.Squared initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SquaredApp.SquaredHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SquaredApp.SquaredHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SquaredApp.SquaredHelper.type ();
  }

}
