package SquaredApp;


/**
* SquaredApp/SquaredOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Squared.idl
* Saturday, April 10, 2021 8:59:48 PM SGT
*/

public interface SquaredOperations 
{
  String getSquare (double input);
  String getSquareRoot (double input);
} // interface SquaredOperations
